backend:
  name: git-gateway        # Uses Git Gateway to interact with GitHub
  branch: main             # Default branch of your Git repository (use 'main' or 'master')

media_folder: "static/img"    # Folder for uploading images and media files
public_folder: "/img"         # Publicly accessible images folder

collections:
  - name: "blog"             # Name of the content type (e.g., blog posts)
    label: "Blog"            # How this content type is labeled in the admin panel
    folder: "content/blog"    # The folder where blog posts are stored (in your repository)
    create: true             # Allow creating new posts
    fields:
      - { label: "Title", name: "title", widget: "string" }      # Title field for the blog post
      - { label: "Date", name: "date", widget: "datetime" }      # Date field for the post
      - { label: "Body", name: "body", widget: "markdown" }      # Content of the post (markdown)
