backend:
  name: git-gateway
  branch: main # or your deployment branch

media_folder: "static/images/uploads" # Folder where uploaded images are stored
public_folder: "/images/uploads"      # Public URL for the images

collections:
  - name: "blog"          # Used in routes, e.g., /admin/collections/blog
    label: "Blog"         # Admin UI Label
    folder: "_posts"      # Folder where your blog posts are stored
    create: true          # Allow new blog posts
    slug: "{{slug}}"      # URL structure
    fields:               # Fields for each blog post
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
